version: '3'

services:
  backend:
    image: '${WEB_IMAGE}'
    command: gunicorn {{ project_name }}.wsgi:application -w 4 -b 0.0.0.0:8000 --chdir=/usr/src/app --log-file -
    volumes:
      - ./docker/mnt/flags/:/mnt/flags/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file: .env
    restart: always

  nginx:
    image: '${NGINX_IMAGE}'
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 30080:80
    restart: always
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
